### ISSUE TITLE
有mac方案吗？

### ISSUE THREAD

**Issue by wwy2018** [lovetingyuan/free-ss#3]
这个翻墙的实现原理是什么啊？mac能开发这样的小程序吗？

**Comment by lovetingyuan** [comment]
@jowang2016 基于https://github.com/shadowsocks/shadowsocks-windows实现的翻墙，我所做的只是抓取账号而已，mac貌似没有，不太清楚

**Comment by lovetingyuan** [comment]
目前只支持windows和android平台
