### ISSUE TITLE
node:6092 错误？

### ISSUE THREAD

**Issue by hohohahahehe** [lovetingyuan/free-ss#6]
(node:6092) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): TypeError: Cannot read property 'message' of undefined

win7 64bit，敲入ss有如上的提示
请问？？

**Comment by lovetingyuan** [comment]
不好意思 正在发布新版本，但是最近比较忙 回去弄下，谢谢关注
