### ISSUE TITLE
ss 失效

### ISSUE THREAD

**Issue by ZoolYe** [lovetingyuan/free-ss#7]
已经失效了？不能正常使用了，第一次执行ss命令会启动Shadowsocks，但是不能科学上网，再次启动后，出现网络连接错误，之后就一直卡在这个界面，等多久都没用，求修复下。
![qq 20170928175740](https://user-images.githubusercontent.com/7373629/30960795-b12a6970-a476-11e7-8d74-882f65fc14ac.jpg)

**Comment by ZoolYe** [comment]
![qq 20170928235126](https://user-images.githubusercontent.com/7373629/30976709-0d8326c2-a4a8-11e7-9448-7c3479839766.jpg)

**Comment by lovetingyuan** [comment]
抱歉， 我会尽快修复

**Comment by e-clin** [comment]
同问：

```
npm install -g --production freess
npm install -g freess
```

执行都没问题，但

`ss`

无法使用，提示如下（没有翻墙连截图都传不上吗？）

freess: 请稍候（3.0.8） ...
freess: 正在配置...
freess: 正在设置账号...
freess: 抱歉，发生了错误：getaddrinfo ENTFOUND tingyuan.me tingyuan.me:443

**Comment by lovetingyuan** [comment]
我的网站被举报了。。。

**Comment by e-clin** [comment]
谁特么干这种损人不利己的缺德事！！
